python=/nfs/volume-100003-1/raochongzhi/envs/tf_a6000/bin/python
hadoop="/usr/local/hadoop-current/bin/hadoop"
hadoop_jar=/usr/local/hadoop-current/share/hadoop/tools/lib/hadoop-streaming-2.7.2-1906.jar
hadoopstreaming="${hadoop} jar ${hadoop_jar} -D stream.non.zero.exit.is.failure=false"
hadoop_queue="root.soda_i18n_trading_stg_prod"
hdfs_prefix="hdfs://DClusterUS1"

#fea path
hadoop_fea_root=/user/prod_soda_trade_strategy/rank/zhangshuai/MX/mew_sam/
hadoop_fea_ins_input=$hadoop_fea_root"/fea_extract"
hadoop_data=$hadoop_root"/data"
train_hdfs_dir="${hdfs_prefix}${hadoop_fea_root}/data_df_all"
test_hdfs_dir="${hdfs_prefix}${hadoop_fea_root}/data_df_all"

#model path
hadoop_root=/user/prod_soda_trade_strategy/rank/chenpinyuan/train_model/tf_train_v2_luban_act_relax_ana_slot/
hadoop_serving_model=$hadoop_root"/serving_model"

is_auto_train=0
need_dump_serving_model=1

train_start_day=20251101
train_end_day=20260711
test_start_day=20260712
test_end_day=20260715

#submit luban user and path
USER_UUID="fb8b6210117a4930b598581b5a1da5fa"
JOB_NAME="tf_train_v2_luban_act_relax_ana_slot"
SCRIPT_PATH="/nfs/dataset-ofs-rank-ssl/chenpinyuan/tf_rank/tf_train_v2_luban_act_relax_ana_slot/train.sh"
RESOURCE_UUID="8d053ced94df4883837eb91a1afa9a87"
PRIORITY=1
