python=/nfs/volume-100003-1/raochongzhi/envs/tf_a6000/bin/python
hadoop="/usr/local/hadoop-current/bin/hadoop"
hadoop_jar=/usr/local/hadoop-current/share/hadoop/tools/lib/hadoop-streaming-2.7.2-1906.jar
hadoopstreaming="${hadoop} jar ${hadoop_jar} -D stream.non.zero.exit.is.failure=false"
hadoop_queue="root.soda_i18n_trading_stg_prod"
hdfs_prefix="hdfs://DClusterUS1"

#fea path
hadoop_fea_root=/user/prod_soda_trade_strategy/rank/zhangshuai/MX/mew_sam/
hadoop_fea_ins_input=$hadoop_fea_root"/fea_extract"
hadoop_data=$hadoop_root"/data"
train_hdfs_dir="${hdfs_prefix}${hadoop_fea_root}/data_df_all"
test_hdfs_dir="${hdfs_prefix}${hadoop_fea_root}/data_df_all"

#model path
#hadoop_root=/user/prod_soda_trade_strategy/rank/zhangshuai/MX/mx_rank_din_lhuc_all
hadoop_root=/user/prod_soda_trade_strategy/rank/zhangshuai/MX/mx_rank_din_lhuc_gama
hadoop_serving_model=$hadoop_root"/serving_model"

is_auto_train=1
need_dump_serving_model=1

train_start_day=20260711
train_end_day=20260711
test_start_day=20260705
test_end_day=20260705

#submit luban user and path
USER_UUID="a41a1f9bf2ee46a5848b1dd21726501e"
JOB_NAME="tf_train_v2_luban_act_new_sam"
SCRIPT_PATH="/nfs/dataset-ofs-rank-ssl/zhangshuai/rank/mx/tf_train_v2_luban_act_gama/train.sh"
RESOURCE_UUID="8d053ced94df4883837eb91a1afa9a87"
#RESOURCE_UUID="9b208bb200fd4af5a0182ec719337307"
PRIORITY=1

