# fea_size only for owlqn
fea_size=519300
# enable_sample:0 no samplling; 1 negtive under sample; 2 pv level negtive under sample, pv label must be add to the final add token 
enable_sample=1
sample_rate=0.05
# 是否归一化
enable_zscore=0
# 是否过滤slot
enable_fea_filt=0
fea_filt_slot_conf=./model/fea_filt_slot.conf
zscore_file=./model/predictor.zscore
